version: '3.4'

services:
  carcatalog.postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5431:5431"
    command: 
      - "postgres"
      - "-c"
      - "port=5431"
    networks:
      - shared.carcatalog.net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  carcatalog.redis:
    ports:
      - '6379:6379'
    networks:
      - shared.carcatalog.net
    volumes:      
      - ~/.docker-conf/redis/data/:/data

  carcatalog.api:
    ports:
      - "10000:80"
    networks:
      - shared.carcatalog.net
    env_file:
      - env.api

  carcatalog.identity:
    ports:
      - "10001:80"
    networks:
      - shared.carcatalog.net
    env_file:
      - env.identity

networks:
  shared.carcatalog.net:
    name: car_catalog_net
    driver: bridge