version: '3.4'

services:

  carcatalog.postgresql:
    image: postgres:14.1
    
  carcatalog.redis:
    image: redis

  carcatalog.rabbitmq:
    image: rabbitmq:management

  carcatalog.api:
    image: ${DOCKER_REGISTRY-}carcatalogapi
    build:
      context: .
      dockerfile: Systems/Api/CarCatalog.Api/Dockerfile
    depends_on:
      - carcatalog.postgresql
      - carcatalog.redis

  carcatalog.identity:
    image: ${DOCKER_REGISTRY-}carcatalogidentity
    build:
      context: .
      dockerfile: Systems/Identity/CarCatalog.Identity/Dockerfile
    depends_on:
      - carcatalog.postgresql
      - carcatalog.redis
      - carcatalog.api

  carcatalog.worker_1:
    image: ${DOCKER_REGISTRY-}carcatalogworker
    build:
      context: .
      dockerfile: Systems/Workers/CarCatalog.Worker/Dockerfile
    depends_on:
      - carcatalog.postgresql
      - carcatalog.redis
      - carcatalog.rabbitmq
      - carcatalog.api

  carcatalog.worker_2:
    image: ${DOCKER_REGISTRY-}carcatalogworker
    build:
      context: .
      dockerfile: Systems/Workers/CarCatalog.Worker/Dockerfile
    depends_on:
      - carcatalog.postgresql
      - carcatalog.redis
      - carcatalog.rabbitmq
      - carcatalog.api

  carcatalog.web:
    image: ${DOCKER_REGISTRY-}carcatalogweb
    build:
      context: .
      dockerfile: Systems/Web/CarCatalog.Web/Dockerfile
    depends_on:
      - carcatalog.postgresql
      - carcatalog.redis
      - carcatalog.rabbitmq
      - carcatalog.api
